import { db, finishRun, startRun } from "../../db";
import { countryGeoAreaId, resolveGeoArea } from "../../geo";
import { fetchAndSnapshot } from "../raw";
const ENDPOINT="https://si3.bcentral.cl/SieteRestWS/SieteRestWS.ashx";const FREQUENCIES=["DAILY","MONTHLY","QUARTERLY","ANNUAL"];
type Series={seriesId:string;frequencyCode?:string;spanishTitle?:string;englishTitle?:string;firstObservation?:string;lastObservation?:string;updatedAt?:string;[key:string]:unknown};type Obs={indexDateString?:string;value?:string|number;statusCode?:string;[key:string]:unknown};
const arr=<T>(v:T|T[]|null|undefined):T[]=>v==null?[]:Array.isArray(v)?v:[v];
function iso(v?:string){if(!v)return null;if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;const m=/^(\d{2})-(\d{2})-(\d{4})$/.exec(v);return m?`${m[3]}-${m[2]}-${m[1]}`:null}function nextDay(v:string){const d=new Date(`${v}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)}
function url(token:string,params:Record<string,string>){const u=new URL(ENDPOINT);u.searchParams.set("token",token);for(const[k,v]of Object.entries(params))u.searchParams.set(k,v);return u.toString()}
async function request(token:string,run:number,params:Record<string,string>){const raw=await fetchAndSnapshot("bcentral",run,url(token,params));const json=JSON.parse(raw.text);if(Number(json.Codigo??0)!==0)throw new Error(`BCCh ${json.Codigo}: ${json.Descripcion??"error"}`);return{json,snapshotId:raw.snapshotId}}
async function discover(token:string,run:number){const map=new Map<string,Series>();for(const frequency of FREQUENCIES){const{json}=await request(token,run,{function:"SearchSeries",frequency});const list=arr<Series>(json.SeriesInfos);console.log(`[bcentral] ${frequency}: ${list.length} series`);for(const s of list)if(s.seriesId)map.set(s.seriesId,s)}return[...map.values()]}
function seriesGeo(s:Series){const title=s.spanishTitle??s.englishTitle??"";const regional=resolveGeoArea(null,title);return regional?{id:regional,scope:"region"}:{id:countryGeoAreaId(),scope:"country"}}
function saveCatalog(s:Series){const title=s.spanishTitle??s.englishTitle??s.seriesId;const geo=seriesGeo(s);db.prepare(`INSERT INTO source_catalog_items(source_id,external_id,title,description,publisher,page_url,metadata_json,updated_at) VALUES('bcentral',?,?,?,?,?,?,?) ON CONFLICT(source_id,external_id) DO UPDATE SET title=excluded.title,description=excluded.description,metadata_json=excluded.metadata_json,updated_at=excluded.updated_at`).run(s.seriesId,title,s.englishTitle??null,"Banco Central de Chile","https://si3.bcentral.cl/Siete/ES/Siete",JSON.stringify(s),iso(s.updatedAt)??s.updatedAt??null);db.prepare(`INSERT INTO metric_definitions(source_id,external_id,title,description,category,subcategory,unit,frequency,geo_scope,metadata_json) VALUES('bcentral',?,?,?,?,?,?,?,?,?) ON CONFLICT(source_id,external_id) DO UPDATE SET title=excluded.title,description=excluded.description,frequency=excluded.frequency,geo_scope=excluded.geo_scope,metadata_json=excluded.metadata_json`).run(s.seriesId,title,s.englishTitle??null,"economia",null,null,s.frequencyCode??null,geo.scope,JSON.stringify(s))}
async function syncSeries(token:string,run:number,s:Series){const row=db.prepare(`SELECT MAX(observed_at) latest FROM observations WHERE source_id='bcentral' AND metric=?`).get(s.seriesId)as{latest:string|null}|null;const first=row?.latest?nextDay(row.latest.slice(0,10)):(iso(s.firstObservation)??"1900-01-01");const last=iso(s.lastObservation)??new Date().toISOString().slice(0,10);if(first>last)return{seen:0,written:0};const{json,snapshotId}=await request(token,run,{function:"GetSeries",timeseries:s.seriesId,firstdate:first,lastdate:last});const list=arr<Obs>(json.Series?.Obs);const geo=seriesGeo(s).id;const stmt=db.prepare(`INSERT INTO observations(source_id,external_id,observed_at,metric,value_number,value_text,unit,geo_area_id,subject_type,subject_id,raw_snapshot_id,payload_json) VALUES('bcentral',?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(source_id,external_id,metric) DO UPDATE SET observed_at=excluded.observed_at,value_number=excluded.value_number,value_text=excluded.value_text,geo_area_id=excluded.geo_area_id,raw_snapshot_id=excluded.raw_snapshot_id,payload_json=excluded.payload_json`);let written=0;db.transaction(()=>{for(const o of list){const date=iso(o.indexDateString);if(!date)continue;const n=Number(o.value);const numeric=Number.isFinite(n)?n:null;stmt.run(`${s.seriesId}:${date}`,date,s.seriesId,numeric,numeric===null&&o.value!=null?String(o.value):null,null,geo,"statistical_series",s.seriesId,snapshotId,JSON.stringify({series:s,observation:o}));written++}})();return{seen:list.length,written}}
export async function syncBCentral(){const token=process.env.BCCH_API_KEY?.trim();if(!token)throw new Error("Falta BCCH_API_KEY en .env");const run=startRun("bcentral");let seen=0,written=0,failed=0;try{const series=await discover(token,run);for(const s of series)saveCatalog(s);await Bun.write("data/bcentral-series.json",JSON.stringify({discoveredAt:new Date().toISOString(),series:series.map(s=>({id:s.seriesId,name:s.spanishTitle??s.englishTitle??s.seriesId,frequency:s.frequencyCode,firstObservation:s.firstObservation,lastObservation:s.lastObservation}))},null,2)+"\n");const concurrency=Math.max(1,Number(process.env.BCCH_CONCURRENCY??"2")||2);let cursor=0,done=0;await Promise.all(Array.from({length:concurrency},async()=>{while(true){const i=cursor++;if(i>=series.length)return;try{const r=await syncSeries(token,run,series[i]);seen+=r.seen;written+=r.written}catch(e){failed++;console.error(`[bcentral] ${series[i].seriesId}: ${String(e)}`)}done++;if(done%25===0||done===series.length)console.log(`[bcentral] ${done}/${series.length} series · obs=${seen} written=${written} failed=${failed}`)}}));finishRun(run,"success",`series=${series.length}; failed=${failed}`,seen,written);return{series:series.length,seen,written,failed,concurrency}}catch(e){finishRun(run,"failed",String(e),seen,written);throw e}}
